unique_ids:
  assets:
    standard-page.html: J77K5I3DKSEWWBLQW5DJOZA2HA5CRBE4
    theme.css: WEZYCCCR4CKK3JG7WOHTSRYHPH5YCQTD
  forms:
    Form1: EWXB3JI6U4DQ76GO55RY3GDNZADCWIF4
  modules: {}
  scripts: {}
  server_modules: {}
